### PR TITLE
Add npm tasks to generate typescript documentation

### PR DESCRIPTION
**Pull request by thomaschampagne**
For my own (and others?! :)) understanding of your project/api i decided to generate the typescript documentation.

**Example of the Activity class:**

image

With this PR simply run:

```
npm install
npm run generate:docs
```

You will get the html docs in `./docs` folder of the project.

---
**PR side note:**

You can go further by publishing your docs automatically to github pages to get something like this https://thomaschampagne.github.io/promise-tron/

I have npm task entry point for this: https://github.com/thomaschampagne/promise-tron/blob/develop/package.json#L35

Let me know if you want my help for this.

### CODE REVIEW

**Comment by thomaschampagne** [comment]
Travis CI fails because of legacy tests in failures :(

**Comment by jimmykane** [comment]
Why closed ?

**Comment by jimmykane** [comment]
Was about to merge this :-(

**Comment by thomaschampagne** [comment]
Oh dear. Mistake from me. I deleted the branch on my repo. Let  me recover this

**Comment by thomaschampagne** [comment]
Should be live again.

**Comment by jimmykane** [comment]
Perfect. Thank you. I will try to get this merged by the end of the day.

**Pull request merged**
